version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: studioops-postgres
    environment:
      POSTGRES_DB: studioops
      POSTGRES_USER: studioops
      POSTGRES_PASSWORD: studioops123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U studioops -d studioops"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: studioops-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: studioops
      MINIO_ROOT_PASSWORD: studioops123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  langfuse:
    image: langfuse/langfuse:latest
    container_name: studioops-langfuse
    ports:
      - "3100:3000"
    environment:
      DATABASE_URL: postgresql://studioops:studioops123@postgres:5432/studioops
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-your-secret-here}
      NEXTAUTH_URL: http://localhost:3100
      LANGFUSE_SECRET: ${LANGFUSE_SECRET:-your-langfuse-secret}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/public/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build:
      context: ../apps/api
      dockerfile: Dockerfile
    container_name: studioops-api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://studioops:studioops123@postgres:5432/studioops
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: studioops
      MINIO_SECRET_KEY: studioops123
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY:-}
      LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY:-}
      LANGFUSE_HOST: http://langfuse:3100
      OPENAI_API_KEY: ${OPENAI_API_KEY:-sk-mock-key}
    volumes:
      - ../apps/api:/app
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      langfuse:
        condition: service_healthy

volumes:
  postgres_data:
  minio_data: